### ISSUE TITLE
Beta 12 Silent crash when switching desktops via CTRL+WIN+Arrow on 22621.2361

### ISSUE THREAD

**Issue by andyylin** [hwtnb/SylphyHornPlusWin11#35]
SylphyHorn Beta 12 loads just fine on the latest Windows version, and shows the current desktop number properly. But when I switch to another desktop via CTRL+WIN+arrow key, SylphyHorn silently crashes and the desktop number disappears from the system tray.

**Comment by hwtnb** [comment]
I haven't checked it yet, but it is similar to the issue for beta.10 on build 23526 or later.
If you have updated from beta.10, try deleting cache data (``VirtualDesktop.*****.generated.dll``) at ``%UserProfile%\AppData\Local\hwtnb.net\SylphyHorn\assemblies``.

**Comment by bobsage123** [comment]
> I haven't checked it yet, but it is similar to the issue for beta.10 on build 23526 or later. If you have updated from beta.10, try deleting cache data (`VirtualDesktop.*****.generated.dll`) at `%UserProfile%\AppData\Local\hwtnb.net\SylphyHorn\assemblies`.

Clearing the cache seems to have resolved this for me.

**Comment by andyylin** [comment]
Confirmed, this resolves the issue for me too.

> I haven't checked it yet, but it is similar to the issue for beta.10 on build 23526 or later. If you have updated from beta.10, try deleting cache data (`VirtualDesktop.*****.generated.dll`) at `%UserProfile%\AppData\Local\hwtnb.net\SylphyHorn\assemblies`.
