### ISSUE TITLE
Cannot start on Windows 11 Pro 23H2 22635.2915

### ISSUE THREAD

**Issue by andyylin** [hwtnb/SylphyHornPlusWin11#41]
Program refuses to start after the recent Windows update.

**Comment by eggbean** [comment]
There are already a few threads regarding this.

eg. https://github.com/hwtnb/SylphyHornPlusWin11/issues/36

**Comment by andyylin** [comment]
Thanks, I didn't realize.  I'll close this.

**Comment by dlrourke** [comment]
This should not have been closed.  The new Windows version 23H2 (OS Build 22635.2915) broke SylphyHornPlusWin11... again.

**Comment by eggbean** [comment]
Crap, not again. I have paused updates, but it says I can only pause it for a week. I'm making my internet connection a metered one, so it doesn't download any updates, which will hopefully delay it for longer.
