### ISSUE TITLE
Settings Windows crash when you wallpaper is plain color

### ISSUE THREAD

**Issue by imagicalFantasy** [hwtnb/SylphyHornPlusWin11#6]
the last functional version was SylphyHorn.Win11Test6

In my case, I'm using wallpaper engine, so I don't set Windows wallpaper and the tool can't open windows when you don't have seted wallpaper.

System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à SylphyHorn.Serialization.SerializationExtensions.GetOrDefault(WallpaperPathProperty path)
   à SylphyHorn.UI.Bindings.WallpaperViewModel..ctor(VirtualDesktop desktop, WallpaperPathProperty path, WallpaperPositionsProperty position)
   à SylphyHorn.UI.Bindings.VirtualDesktopViewModel..ctor(Int32 index, VirtualDesktop desktop)
   à SylphyHorn.UI.Bindings.VirtualDesktopViewModel.<>c.<CreateAll>b__37_0(VirtualDesktop d, Int32 i)
   à System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   à System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   à System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   à SylphyHorn.UI.Bindings.SettingsWindowViewModel..ctor(HookService hookService)
   à SylphyHorn.ApplicationPreparation.ShowSettings()
   à System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   à System.Windows.Forms.MenuItem.MenuItemData.Execute()
   à System.Windows.Forms.Command.Invoke()
   à System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4510.0 built by: NET48REL1LAST_B
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SylphyHorn
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.0.0
    CodeBase : file:///E:/Addon/SylphyHorn/SylphyHorn.exe
----------------------------------------
PresentationFramework
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4470.0
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
MetroTrilithon
    Version de l'assembly : 0.3.0.0
    Version Win32 : 0.3.0.0
    CodeBase : file:///E:/Addon/SylphyHorn/lib/MetroTrilithon.DLL
----------------------------------------
netstandard
    Version de l'assembly : 2.0.0.0
    Version Win32 : 4.8.4161.0
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.ApplicationInsights
    Version de l'assembly : 2.20.0.103
    Version Win32 : 2.20.0.00103
    CodeBase : file:///E:/Addon/SylphyHorn/lib/Microsoft.ApplicationInsights.DLL
----------------------------------------
System.Diagnostics.DiagnosticSource
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.21.52210
    CodeBase : file:///E:/Addon/SylphyHorn/lib/System.Diagnostics.DiagnosticSource.DLL
----------------------------------------
System.Xml.Linq
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4161.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Net.Http
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4161.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4161.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
StatefulModel
    Version de l'assembly : 0.1.0.0
    Version Win32 : 0.1.0.0
    CodeBase : file:///E:/Addon/SylphyHorn/lib/StatefulModel.DLL
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
MetroRadiance
    Version de l'assembly : 2.4.1.0
    Version Win32 : 2.4.1.0
    CodeBase : file:///E:/Addon/SylphyHorn/lib/MetroRadiance.DLL
----------------------------------------
MetroTrilithon.Desktop
    Version de l'assembly : 0.3.1.0
    Version Win32 : 0.3.1.0
    CodeBase : file:///E:/Addon/SylphyHorn/lib/MetroTrilithon.Desktop.DLL
----------------------------------------
PresentationFramework.Aero2
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4161.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
Livet.Mvvm
    Version de l'assembly : 4.0.2.0
    Version Win32 : 4.0.2
    CodeBase : file:///E:/Addon/SylphyHorn/lib/Livet.Mvvm.DLL
----------------------------------------
SylphyHorn.Core
    Version de l'assembly : 0.3.0.0
    Version Win32 : 0.3.0.0
    CodeBase : file:///E:/Addon/SylphyHorn/lib/SylphyHorn.Core.DLL
----------------------------------------
System.Runtime.Serialization
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.ServiceModel
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
VirtualDesktop
    Version de l'assembly : 4.0.1.0
    Version Win32 : 4.0.1.0
    CodeBase : file:///E:/Addon/SylphyHorn/lib/VirtualDesktop.DLL
----------------------------------------
GregsStack.InputSimulatorStandard
    Version de l'assembly : 1.3.3.0
    Version Win32 : 1.3.3.0
    CodeBase : file:///E:/Addon/SylphyHorn/lib/GregsStack.InputSimulatorStandard.DLL
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Management
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Runtime.Remoting
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4161.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
MetroRadiance.Core
    Version de l'assembly : 2.4.1.0
    Version Win32 : 2.4.1.0
    CodeBase : file:///E:/Addon/SylphyHorn/lib/MetroRadiance.Core.DLL
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
Open.WinKeyboardHook
    Version de l'assembly : 1.0.14.0
    Version Win32 : 1.0.14.0
    CodeBase : file:///E:/Addon/SylphyHorn/lib/Open.WinKeyboardHook.DLL
----------------------------------------
VirtualDesktop.22000.generated
    Version de l'assembly : 1.0.0.21359
    Version Win32 : 1.0.0.21359
    CodeBase : file:///D:/Claude/AppData/Local/grabacr.net/SylphyHorn/assemblies/VirtualDesktop.22000.generated.dll
----------------------------------------
MetroRadiance.Chrome
    Version de l'assembly : 2.2.0.0
    Version Win32 : 2.2.0.0
    CodeBase : file:///E:/Addon/SylphyHorn/lib/MetroRadiance.Chrome.DLL
----------------------------------------
Microsoft.Xaml.Behaviors
    Version de l'assembly : 1.1.0.0
    Version Win32 : 1.1.39.4716
    CodeBase : file:///E:/Addon/SylphyHorn/lib/Microsoft.Xaml.Behaviors.DLL
----------------------------------------
Livet.Behaviors
    Version de l'assembly : 4.0.2.0
    Version Win32 : 4.0.2
    CodeBase : file:///E:/Addon/SylphyHorn/lib/Livet.Behaviors.DLL
----------------------------------------
Livet.Core
    Version de l'assembly : 4.0.2.0
    Version Win32 : 4.0.2
    CodeBase : file:///E:/Addon/SylphyHorn/lib/Livet.Core.DLL
----------------------------------------
Livet.Messaging
    Version de l'assembly : 4.0.2.0
    Version Win32 : 4.0.2
    CodeBase : file:///E:/Addon/SylphyHorn/lib/Livet.Messaging.DLL
----------------------------------------
PresentationFramework-SystemXmlLinq
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4161.0
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXmlLinq/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXmlLinq.dll
----------------------------------------
PresentationFramework.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4161.0
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.resources/v4.0_4.0.0.0_fr_31bf3856ad364e35/PresentationFramework.resources.dll
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4161.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Livet.EventListeners
    Version de l'assembly : 4.0.2.0
    Version Win32 : 4.0.2
    CodeBase : file:///E:/Addon/SylphyHorn/lib/Livet.EventListeners.DLL
----------------------------------------
Livet.Collections
    Version de l'assembly : 4.0.2.0
    Version Win32 : 4.0.2
    CodeBase : file:///E:/Addon/SylphyHorn/lib/Livet.Collections.DLL
----------------------------------------
Windows.ApplicationModel
    Version de l'assembly : 255.255.255.255
    Version Win32 : 10.0.10011.16384
    CodeBase : file:///C:/Windows/system32/WinMetadata/Windows.ApplicationModel.winmd
----------------------------------------
Windows.Foundation
    Version de l'assembly : 255.255.255.255
    Version Win32 : 10.0.10011.16384
    CodeBase : file:///C:/Windows/system32/WinMetadata/Windows.Foundation.winmd
----------------------------------------
QTTabBar
    Version de l'assembly : 1.0.0.0
    Version Win32 : 2048.0.0.0
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/QTTabBar/v4.0_1.0.0.0__78a0cde69b47ca25/QTTabBar.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4161.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Accessibility
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4161.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
PresentationCore.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4161.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationCore.resources/v4.0_4.0.0.0_fr_31bf3856ad364e35/PresentationCore.resources.dll
----------------------------------------
UIAutomationProvider
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
UIAutomationTypes
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Version de l'assembly : 0.0.0.0
    Version Win32 : 4.8.4510.0 built by: NET48REL1LAST_B
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

**Comment by sfranky** [comment]
I have the same problem...
Windows 11 Version	10.0.22000 Build 22000
This is an otherwise EXCELLENT program, thank you for your work!!!
running beta 4

**Comment by YxT3** [comment]
Same problem here on Windows.11 Pro x64, version '21H2 (OS Build 22000.856) while having a unicolor "Solid Color" wallpaper as Background under Personalisation in Windows Settings.
In these circumstances :::
Taskbar tray's SylphyHornPlus icon > Right.Click > Settings > :::
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SylphyHorn.Serialization.SerializationExtensions.GetOrDefault(**Wallpaper**PathProperty path)
   at SylphyHorn.UI.Bindings.WallpaperViewModel..ctor(VirtualDesktop desktop,**Wallpaper**PathProperty path, WallpaperPositionsProperty position)
   at SylphyHorn.UI.Bindings.VirtualDesktopViewModel..ctor(Int32 index, VirtualDesktop desktop)
   at SylphyHorn.UI.Bindings.VirtualDesktopViewModel.<>c.<CreateAll>b__37_0(VirtualDesktop d, Int32 i)
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SylphyHorn.UI.Bindings.SettingsWindowViewModel..ctor(HookService hookService)
   at SylphyHorn.ApplicationPreparation.**ShowSettings**()
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
- - -
No such problem formerly on Windows.10 when running ViRb3's more original SylphyHornEx.
- - -
Of course a very easy work-around to this problem is found in assignment of a file-based wallpaper to even only a single desktop in Windows_Settings > Personalisation > Background.
- - -
Regarding the original post on this issue, issue opener imagicalFantasy should preferably reduce the "profile" of their 27_May 2022 Assembly list, for a less invasive posting and for sake of easier readability,

**Comment by hwtnb** [comment]
Thank you for your report.

Please try the pre-release binary that includes this bug fix, the link is here: https://github.com/hwtnb/SylphyHornPlusWin11/releases/download/v4.0.0-beta.5/SylphyHornPlus-Ver4.0.0-beta.5-fix11InsiderBuild25158.zip

**Comment by hwtnb** [comment]
I have released [beta.6](https://github.com/hwtnb/SylphyHornPlusWin11/releases/tag/v4.0.0-beta.6), so the issue is closed.
