### ISSUE TITLE
window 11 preview support

### ISSUE THREAD

**Issue by bourbon08** [hwtnb/SylphyHornPlusWin11#7]
this app is work fine on my computer with version Windows 11 Insider Preview 25151.1000 
, but latter version is not supported

**Comment by hwtnb** [comment]
@bourbon08 Thank you for your report.

Unfortunately, COM API (IID) is changed again on recent Windows 11 Insider Preview (Dev) but I found new IID.

I'm now fixing the issue. Please try the test binary, the link is here: https://github.com/hwtnb/SylphyHornPlusWin11/releases/download/v4.0.0-beta.5/SylphyHornPlus-Ver4.0.0-beta.5-fix11InsiderBuild25158.zip
Please delete cache data before startup. I tested it on build 25179.

**Comment by bourbon08** [comment]
@hwtnb it works on build 25174. Thanks a lot!
